project: 
  type: website
  output-dir: _site
  
  
website: 
  page-navigation: true
  title: "Studiereis Dairyconsult naar Italië" 
  site-url: "https://albartcoster.github.io/studiereis_italie/" 
  repo-url: https://github.com/albartcoster/studiereis_italie
  ## repo-actions: [edit] ## ,issue3
  
  page-footer:
    right: "Pagina gemaakt met plezier en met [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Albart Coster, 2026"
    
  sidebar:
    logo: "images/DC.webp"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.dairyconsult.nl
        text: "Dairyconsult.nl"
      - icon: github
        href: https://github.com/albartcoster/studiereisitalie
        text: "Studiereis"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welkom/Bienvenida
      - href: planning.qmd
        text: Planning van de reis
      - href: kaart.qmd
        text: Kaart van reis

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      ## dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    email-obfuscation: references
    link-external-icon: false


filters:
  - include-files.lua
  - quarto

  
