---
title: "Milaan"
---

Milaan, het einde van de excursie: de tweede stad van Italië die samen met de omliggende steden vier miljoen inwoners telt. Gesticht midden in de vlakte rond 600 vC. door een Keltische stam. In de nadagen van het Romeinse Rijk, toen de keizerszetel verplaatst was naar Constantinopel (Byzantium, Istanboel), was Milaan de administratieve hoofdstad van  het westen. Reeds had toen de de stad haar naam gegeven aan het Edict van Milaan (313 nC.), waarbij keizer Constantijn de Grote rechtsbescherming gaf aan de christenen. In diezelfde eeuw was Milaan de stad waar de Afrikaan Augustinus van Hippo het christelijk geloof omarmde, om vervolgens grote invloed uit te oefenen op de Europese cultuur. Na de val van het Rijk in het westen (V eeuw) passeren achtereenvolgens de Hunnen, de Goten en de Longobarden, totdat Milaan in de VIII eeuw deel wordt van het Rijk van Karel de Grote. In de Middeleeuwen is Mailand formeel deel van het Duitse keizerrijk, maar in feite een onafhankelijk hertogdom met grote culturele status. Na enkele eeuwen aan de Habsburgers onderworpen te zijn geweest wordt de stad in 1861 deel van het verenigde koninkrijk Italië. 

Op donderdagavond 29 oktober zullen we een rondje door het centrum van Milaan maken, geleid door Berend Coster. Het is bijna uitgesloten dat we het beroemde Laatste Avondmaal van Leonardo da Vinci in de Santa Maria della Grazie te zien zullen krijgen, want het bemachtigen van een ticket voor deze kerk is buitengewoon moeilijk. We zullen dus genoegen moeten nemen met een impressie van de stad.



