---
title: "Cristella Holstein"
format: html
---

Cristella Holstein is eigendom van Donatella Belstreri en heeft zijn naam van de twee dochters van de oprichter Franco; Cristina en Donatella. Naast Donatella, de huidige eigenaar en bedrijfsleider zijn haar echtgenoot Vittorio Marchi en hun zonen Tommaso, Umberto en Angelica Contini, Umberto's partner in het bedrijf betrokken. Vittorio Marchi is dierenarts en heeft een leidingevende funktie op een leerstoelgroep van een universiteit. Umberto is verantwoordelijk voor de akkerbouw en Angelica Contini is verantwoordelijk voor de kalveropfok van het bedrijf. Naast de familieleden zijn nog 12 medewerkers actief op het bedrijf.

Genetica, voeding, en dierwelzijn plus automatisering zijn de drie pijlers van het bedrijf. Het bedrijf heeft consequent geïnvesteerd in genetische vooruitgang van de veestapel. De dieren zijn volledig gegenotypeerd voor gPFT (de italiaanse selectieindex) en ook voor gTPI (Genomic Total Performance Index, de genoomvariant van de TPI) en het bedrijf bezit uitzonderlijk goede dieren. Het bedrijf behoort tot de top van de provincie Cremona. Op dit moment zijn 8% van de dieren gekwalificeerd als excellent en zijn er meer dan 30 vaarzen met een TPI boven de 3000.

Op dit moment is de gemiddelde melkproductie 45 kg melk met 4.1% vet en 3.3% eiwit. De gemiddelde piekproductie van oudere koeien overstijgt 50 kg melk. De melk wordt geleverd aan de zuivelcoöperatie Granarolo.

Hier een aantal ontwikkelingen van het bedrijf:

- In 2012 is begonnen met genotyperen van de dieren in samenwerking met ANFIBJ, het italiaanse [stamboek](https://www.anafi.it/).
- In 2018 begonnen met een kleurcoderingssyteem voor vaarzen
- In 2019 is samenwerking met Purina als veevoerleverancier begonnen
- In 2020 installatie van de huidige CMP koelings- en ventilatiesysteem
- In 2021 installatie van de kalverdrinkautomaten
- In 2021 installatie van een nieuwe Boumatic melkstal
- In 2023 begonnen met drie maal daags melken

Het bedrijf telt 550 hectare land.

